### ISSUE TITLE
Motion primitives

### ISSUE THREAD

**Issue by xiaoyuanzh** [gerdl/scc_paths#2] opened 2019-01-09 07:38 UTC
Hi 
    In Scheuer's paper, they consider 9 primitives plus one topological path as options. Here, you consider "PathType.lsl, PathType.lsr,  PathType.rsr, PathType.rsl" 4 types as options. So what is difference, can you codes ensure the shortest one?

**Comment by gerdl** [comment] 2019-01-10 20:05
Duplicate of #1

**Closed as completed** 2019-01-10 20:04 UTC
